[tool.poetry]
name = "json2xml-env"
version = "0.1.0"
description = ""
authors = ["GTrunSec <gtrunsec@hardenedlinux.org>"]

[tool.poetry.dependencies]
python = "^3.9"
json2xml = "^3.19.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
